Ticketshuffle/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :users

  get 'overview' => 'shuffle#overview'
  get 'overview/:id' => 'shuffle#toggleactive'
  put 'overview/:id' => 'shuffle#toggleactive'
  get 'shuffle' => 'shuffle#shuffle'

end

Ticketshuffle/app/models/shuffle.rb
class Shuffle < ActiveRecord::Base
end

Ticketshuffle/app/models/user.rb
class User < ActiveRecord::Base

  def chance
      if (self.tickets == 0)
        if (self.games == 0)
            100
          else
            self.games * 100
          end
      else
        (Float(self.games) / Float(self.tickets)) * 100
      end
  end

end

Ticketshuffle/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ticketshuffle/app/controllers/shuffle_controller.rb
class ShuffleController < ApplicationController
  def overview
    @users = User.all
  end

  def toggleactive
    @user = User.find(params[:id])
    @user.update(active: !@user.active)

    redirect_to :back
  end

  def shuffle
    @users = User.where(active: true) #.to_a.each { |u| u << :chance }
    @totalchanches = 0
    @users.each do |user|
      @totalchanches += user.chance
    end

    @totalchanches = rand(@totalchanches)

    @users.each do |user|
      if (@totalchanches > user.chance)
        @totalchanches -= user.chance
      else
        @winner = user
        user.update_attribute(:tickets, user.tickets += 1)
        break
      end
    end

    @users.each do |user|
      user.update_attribute(:games, user.games += 1)
    end

  end

end

Ticketshuffle/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)

      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :firstname, :lastname, :tickets, :games)
  end
end

Ticketshuffle/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Ticketshuffle/app/helpers/application_helper.rb
module ApplicationHelper
end

Ticketshuffle/app/helpers/shuffle_helper.rb
module ShuffleHelper
end

Ticketshuffle/app/helpers/users_helper.rb
module UsersHelper
end

Ticketshuffle/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Ticketshuffle/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketshuffle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ticketshuffle/app/views/shuffle/overview.html.erb
<h1>Wer ist alles anwesend?</h1><br>

<table>
  <tr>
    <% @users.each do |user| %>
    <td align="center" >
      <p><%= user.nickname %></p>
    </td>

    <% end %>
  </tr>

<tr>
  <% @users.each do |user| %>
    <td>
      <% if user.active %>
        <%= link_to image_tag('call.png', alt: '"designed by freepic', size: '128' ), url_for({controller: :shuffle, action: :toggleactive, id: user.id}) %>
      <% else %>
        <%= link_to image_tag('chair.png', alt: '"designed by freepic', size: '128' ), url_for({controller: :shuffle, action: :toggleactive, id: user.id})  %>
      <% end %>
    </td>
  <% end %>

</tr>
</table>
<br>
<br>
<br>
<h1>Bereit ein Spiel zu spielen?</h1>
<p>
  <%= link_to 'Shuffle', shuffle_path%>
</p>
<br>
<br>
<br>

<%= link_to 'Startseite', root_path %>
<%= link_to 'Supporter', users_path %>

Ticketshuffle/app/views/shuffle/shuffle.html.erb
<h1>Herzlichen Grückwunsch</h1>
<br>
<p><h2><%= @winner.nickname %></h2>
  hat das Ticket gezogen!</p>
<br>
<br>
<%= link_to 'zurück', :back %>

Ticketshuffle/app/views/users/_formular.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>

  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </p>

  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :tickets %><br>
    <%= f.number_field :tickets %>
  </p>

  <p>
    <%= f.label :games %><br>
    <%= f.number_field :games %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<%end%>

Ticketshuffle/app/views/users/edit.html.erb
<h1>Edit Supporter</h1>

<%= render "formular" %>

<%= link_to 'Back', users_path %>

Ticketshuffle/app/views/users/index.html.erb
<h1> Supporter Liste </h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Vorname</th>
    <th>Tickets</th>
    <th>Games</th>
    <th colspan="2"></th>
  </tr>


  <% @users.each do |user| %>
    <tr>
      <td><%= user.lastname %></td>
      <td><%= user.firstname %></td>
      <td><%= user.tickets %></td>
      <td><%= user.games %></td>
      <td><%= link_to 'Show', user_path(user) %> |</td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
    </tr>

  <% end %>

</table>
<br><br>
<%= link_to 'Neuer Supporter', new_user_path %>
<br><br>
<%= link_to 'Startseite', root_path %>

Ticketshuffle/app/views/users/new.html.erb
<h1>New Supporter</h1>

<%= render 'formular' %>

<%= link_to 'Back', users_path %>

Ticketshuffle/app/views/users/show.html.erb
<h1>Supporter</h1>
<p>


  <br>
    <strong>
     <%= @user.lastname %>
  </strong>
  , <%= @user.firstname %>

  <br>
  <%= @user.nickname %> hat schon <%= @user.games %> mitgemacht und <%= @user.tickets %>  Tickets gewonnen.
  <br>

</p>

<br>
<br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Delete', user_path(@user),
  method: :Delete,
  data: { confirm: 'Bist du dir sicher?' } %> |
<%= link_to 'Back', users_path %>

<br>

Ticketshuffle/app/views/welcome/index.html.erb
<h2>Wilkommen</h2>

<p>Dies ist die Startseite zu unserem tollen neuen Ticketshuffler.</p>

<p> Hier gehts lang zu den <%= link_to 'Supportern', users_path%> </p>
<p> Hier gehts lang zu den <%= link_to 'Hungerspielen', overview_path%> </p>